// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oem.Models.Context;

#nullable disable

namespace Oem.Migrations
{
    [DbContext(typeof(OemContext))]
    [Migration("20251227163102_VVEAdded")]
    partial class VVEAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Oem.Models.Domain.OperationPlans.OperationPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AlgorithmRuntimeSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("HeuristicUsed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("ScheduleDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("TotalDelayMinutes")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("OperationPlans", (string)null);
                });

            modelBuilder.Entity("Oem.Models.Domain.OperationPlans.OperationPlanAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangesDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OperationPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OperationPlanId");

                    b.ToTable("OperationPlanAudit");
                });

            modelBuilder.Entity("Oem.Models.Domain.OperationPlans.OperationPlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LoadingEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LoadingStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfCranes")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfStaff")
                        .HasColumnType("integer");

                    b.Property<Guid>("OperationPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ServiceEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ServiceStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UnloadingEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UnloadingStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VesselIMO")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("VesselVisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OperationPlanId");

                    b.ToTable("OperationPlanItems", (string)null);
                });

            modelBuilder.Entity("Oem.Models.Domain.VesselVisitExecutions.VesselVisitExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VesselIMO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VesselVisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("VesselVisitExecutions", (string)null);
                });

            modelBuilder.Entity("Oem.Models.Domain.OperationPlans.OperationPlanAudit", b =>
                {
                    b.HasOne("Oem.Models.Domain.OperationPlans.OperationPlan", "OperationPlan")
                        .WithMany("AuditLog")
                        .HasForeignKey("OperationPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperationPlan");
                });

            modelBuilder.Entity("Oem.Models.Domain.OperationPlans.OperationPlanItem", b =>
                {
                    b.HasOne("Oem.Models.Domain.OperationPlans.OperationPlan", "OperationPlan")
                        .WithMany("Items")
                        .HasForeignKey("OperationPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperationPlan");
                });

            modelBuilder.Entity("Oem.Models.Domain.OperationPlans.OperationPlan", b =>
                {
                    b.Navigation("AuditLog");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
