// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApp.Models.Context;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(PortManagementContext))]
    [Migration("20251215022216_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ActivationInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TempPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ActivationInvites");
                });

            modelBuilder.Entity("DockVesselType", b =>
                {
                    b.Property<Guid>("DockId")
                        .HasColumnType("uuid");

                    b.Property<string>("VesselTypeId")
                        .HasColumnType("character varying(50)");

                    b.HasKey("DockId", "VesselTypeId");

                    b.HasIndex("VesselTypeId");

                    b.ToTable("DockVesselType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ResourceQualificationRequirement", b =>
                {
                    b.Property<string>("ResourceId")
                        .HasColumnType("character varying(50)");

                    b.Property<string>("QualificationCode")
                        .HasColumnType("character varying(50)");

                    b.HasKey("ResourceId", "QualificationCode");

                    b.HasIndex("QualificationCode");

                    b.ToTable("ResourceQualificationRequirements", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Domain.Agents.Representative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CitizenId")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "Email")
                        .IsUnique();

                    b.ToTable("Representatives");
                });

            modelBuilder.Entity("WebApp.Models.Domain.Agents.ShippingAgentOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("AlternativeNames")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AlternativeNames")
                        .IsUnique();

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("LegalName")
                        .IsUnique();

                    b.HasIndex("TaxNumber")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("WebApp.Models.Domain.Containers.Container", b =>
                {
                    b.Property<string>("Identifier")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<Guid?>("CargoManifestId")
                        .HasColumnType("uuid");

                    b.Property<int?>("StorageAreaId")
                        .HasColumnType("integer");

                    b.Property<int>("Teu")
                        .HasColumnType("integer");

                    b.HasKey("Identifier");

                    b.HasIndex("CargoManifestId");

                    b.HasIndex("StorageAreaId");

                    b.ToTable("Containers", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Domain.Docks.Dock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ContainerYardId")
                        .HasColumnType("integer");

                    b.Property<double>("DepthMeters")
                        .HasColumnType("double precision");

                    b.Property<double>("LengthMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("MaxDraftMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ContainerYardId");

                    b.ToTable("Docks", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Domain.Qualifications.Qualification", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Code");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("WebApp.Models.Domain.Resources.Resource", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OperationalCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer");

                    b.Property<int>("SetupTime")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("WebApp.Models.Domain.Staff.QualificationLink", b =>
                {
                    b.Property<string>("StaffMecanographicNumber")
                        .HasColumnType("text");

                    b.Property<string>("QualificationCode")
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("DateObtained")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.HasKey("StaffMecanographicNumber", "QualificationCode");

                    b.HasIndex("QualificationCode");

                    b.ToTable("QualificationLinks");
                });

            modelBuilder.Entity("WebApp.Models.Domain.Staff.Staff", b =>
                {
                    b.Property<string>("MecanographicNumber")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("OperationalWindow")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MecanographicNumber");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("WebApp.Models.Domain.StorageArea.DockStorageAreaConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<Guid>("DockId")
                        .HasColumnType("uuid");

                    b.Property<int>("StorageAreaId")
                        .HasColumnType("integer");

                    b.Property<int>("TravelSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StorageAreaId", "DockId")
                        .IsUnique();

                    b.ToTable("DockStorageAreaConnections");
                });

            modelBuilder.Entity("WebApp.Models.Domain.StorageArea.StorageArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxCapacityTeu")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StorageAreaType")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StorageAreas");

                    b.HasDiscriminator<int>("StorageAreaType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebApp.Models.Domain.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Domain.VesselVisits.CargoManifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LoadingManifestForId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UnloadingManifestForId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LoadingManifestForId")
                        .IsUnique();

                    b.HasIndex("UnloadingManifestForId")
                        .IsUnique();

                    b.ToTable("CargoManifests", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Domain.VesselVisits.CrewMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("VesselVisitNotificationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VesselVisitNotificationId");

                    b.ToTable("CrewMembers", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Domain.VesselVisits.DecisionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VesselVisitNotificationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VesselVisitNotificationId");

                    b.ToTable("DecisionLogs");
                });

            modelBuilder.Entity("WebApp.Models.Domain.VesselVisits.VesselVisitNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DesiredDepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DockId")
                        .HasColumnType("uuid");

                    b.Property<int>("EstimatedLoadingDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("EstimatedUnloadingDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShippingAgentOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VesselIMO")
                        .IsRequired()
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ShippingAgentOrganizationId");

                    b.HasIndex("VesselIMO");

                    b.ToTable("VesselVisitNotifications", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Domain.Vessels.Vessel", b =>
                {
                    b.Property<string>("IMO")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<int>("Bays")
                        .HasColumnType("integer");

                    b.Property<string>("CargoGrid")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("RequiredCraneCount")
                        .HasColumnType("integer");

                    b.Property<double>("RequiredDockLength")
                        .HasColumnType("double precision");

                    b.Property<int>("Rows")
                        .HasColumnType("integer");

                    b.Property<int>("Tiers")
                        .HasColumnType("integer");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("VesselTypeName")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.HasKey("IMO");

                    b.HasIndex("VesselTypeName");

                    b.ToTable("Vessels");
                });

            modelBuilder.Entity("WebApp.Models.Domain.Vessels.VesselType", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("MaxBays")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRows")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTiers")
                        .HasColumnType("integer");

                    b.HasKey("Name");

                    b.ToTable("VesselTypes");
                });

            modelBuilder.Entity("WebApp.Models.Domain.StorageArea.ContainerYard", b =>
                {
                    b.HasBaseType("WebApp.Models.Domain.StorageArea.StorageArea");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("WebApp.Models.Domain.StorageArea.Warehouse", b =>
                {
                    b.HasBaseType("WebApp.Models.Domain.StorageArea.StorageArea");

                    b.Property<string>("SpecializedCargoType")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("DockVesselType", b =>
                {
                    b.HasOne("WebApp.Models.Domain.Docks.Dock", null)
                        .WithMany()
                        .HasForeignKey("DockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Domain.Vessels.VesselType", null)
                        .WithMany()
                        .HasForeignKey("VesselTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebApp.Models.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebApp.Models.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebApp.Models.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResourceQualificationRequirement", b =>
                {
                    b.HasOne("WebApp.Models.Domain.Qualifications.Qualification", null)
                        .WithMany()
                        .HasForeignKey("QualificationCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Domain.Resources.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.Models.Domain.Agents.Representative", b =>
                {
                    b.HasOne("WebApp.Models.Domain.Agents.ShippingAgentOrganization", "Organization")
                        .WithMany("Representatives")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("WebApp.Models.Domain.Containers.Container", b =>
                {
                    b.HasOne("WebApp.Models.Domain.VesselVisits.CargoManifest", null)
                        .WithMany("Containers")
                        .HasForeignKey("CargoManifestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApp.Models.Domain.StorageArea.StorageArea", null)
                        .WithMany("ContainerList")
                        .HasForeignKey("StorageAreaId");
                });

            modelBuilder.Entity("WebApp.Models.Domain.Docks.Dock", b =>
                {
                    b.HasOne("WebApp.Models.Domain.StorageArea.ContainerYard", null)
                        .WithMany("DocksServed")
                        .HasForeignKey("ContainerYardId");
                });

            modelBuilder.Entity("WebApp.Models.Domain.Staff.QualificationLink", b =>
                {
                    b.HasOne("WebApp.Models.Domain.Qualifications.Qualification", "Qualification")
                        .WithMany("QualificationLinks")
                        .HasForeignKey("QualificationCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Domain.Staff.Staff", "Staff")
                        .WithMany("QualificationLinks")
                        .HasForeignKey("StaffMecanographicNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Qualification");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("WebApp.Models.Domain.StorageArea.DockStorageAreaConnection", b =>
                {
                    b.HasOne("WebApp.Models.Domain.StorageArea.StorageArea", null)
                        .WithMany("DockConnections")
                        .HasForeignKey("StorageAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.Models.Domain.VesselVisits.CargoManifest", b =>
                {
                    b.HasOne("WebApp.Models.Domain.VesselVisits.VesselVisitNotification", null)
                        .WithOne("LoadingManifest")
                        .HasForeignKey("WebApp.Models.Domain.VesselVisits.CargoManifest", "LoadingManifestForId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApp.Models.Domain.VesselVisits.VesselVisitNotification", null)
                        .WithOne("UnloadingManifest")
                        .HasForeignKey("WebApp.Models.Domain.VesselVisits.CargoManifest", "UnloadingManifestForId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WebApp.Models.Domain.VesselVisits.CrewMember", b =>
                {
                    b.HasOne("WebApp.Models.Domain.VesselVisits.VesselVisitNotification", null)
                        .WithMany("Crew")
                        .HasForeignKey("VesselVisitNotificationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApp.Models.Domain.VesselVisits.DecisionLog", b =>
                {
                    b.HasOne("WebApp.Models.Domain.VesselVisits.VesselVisitNotification", null)
                        .WithMany("DecisionLogs")
                        .HasForeignKey("VesselVisitNotificationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApp.Models.Domain.VesselVisits.VesselVisitNotification", b =>
                {
                    b.HasOne("WebApp.Models.Domain.Agents.ShippingAgentOrganization", "ShippingAgentOrganization")
                        .WithMany("VesselVisitNotifications")
                        .HasForeignKey("ShippingAgentOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Domain.Vessels.Vessel", "Vessel")
                        .WithMany()
                        .HasForeignKey("VesselIMO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShippingAgentOrganization");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("WebApp.Models.Domain.Vessels.Vessel", b =>
                {
                    b.HasOne("WebApp.Models.Domain.Vessels.VesselType", "VesselType")
                        .WithMany()
                        .HasForeignKey("VesselTypeName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VesselType");
                });

            modelBuilder.Entity("WebApp.Models.Domain.Agents.ShippingAgentOrganization", b =>
                {
                    b.Navigation("Representatives");

                    b.Navigation("VesselVisitNotifications");
                });

            modelBuilder.Entity("WebApp.Models.Domain.Qualifications.Qualification", b =>
                {
                    b.Navigation("QualificationLinks");
                });

            modelBuilder.Entity("WebApp.Models.Domain.Staff.Staff", b =>
                {
                    b.Navigation("QualificationLinks");
                });

            modelBuilder.Entity("WebApp.Models.Domain.StorageArea.StorageArea", b =>
                {
                    b.Navigation("ContainerList");

                    b.Navigation("DockConnections");
                });

            modelBuilder.Entity("WebApp.Models.Domain.VesselVisits.CargoManifest", b =>
                {
                    b.Navigation("Containers");
                });

            modelBuilder.Entity("WebApp.Models.Domain.VesselVisits.VesselVisitNotification", b =>
                {
                    b.Navigation("Crew");

                    b.Navigation("DecisionLogs");

                    b.Navigation("LoadingManifest");

                    b.Navigation("UnloadingManifest");
                });

            modelBuilder.Entity("WebApp.Models.Domain.StorageArea.ContainerYard", b =>
                {
                    b.Navigation("DocksServed");
                });
#pragma warning restore 612, 618
        }
    }
}
